name: kiosk_application
description: "A robust Kiosk Health System."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.0
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  go_router: ^13.0.0
  provider: ^6.1.1
  
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.0.0

  pdf: ^3.11.3
  printing: ^5.14.2
  open_file: ^3.3.0
  encrypt: ^5.0.3
  
  # NEW: For Admin Desktop
  window_manager: ^0.3.9
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.7
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.66.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # HARDWARE
  # HARDWARE
  flutter_libserialport: ^0.6.0
  
  # SYNC & BACKGROUND
  flutter_background_service: any
  flutter_background_service_android: any
  web: ^1.1.1
  js: ^0.6.7
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/patient_icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icons/patient_icon.png"
  notification_icon:
    enabled: true
    image_path: "assets/icons/patient_icon.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/.env
    - assets/icons/
    - assets/animations/
    - assets/config/
    - assets/images/